[package]
name = "example-crate-one"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
libcnb.workspace = true
libherokubuildpack.workspace = true
thiserror.workspace = true

[dev-dependencies]
libcnb-test.workspace = true
